### ISSUE TITLE
Dependency issue with behat-screenshot

### ISSUE THREAD

**Issue by djvern** [acquia/blt-behat#4]
This doesn't install using BLT 12, I think due to the version of behat-screenshot specified in composer.json (^1.2) being incompatible with the latest version of Behat (3.8.1) https://github.com/elvetemedve/behat-screenshot/releases. Can behat-screenshot be updated to 2.1? Also can you create a release tag for this (even if it's alpha or beta) so that I can use it with confidence in a CI environment?

**Comment by danepowell** [comment]
Thanks, I've updated the dependency and cut a stable release.

**Comment by djvern** [comment]
That's perfect, thank you for doing this so quickly @danepowell 😀 .
